/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import org.junit.Assert;
import org.junit.Test;

import java.io.IOException;

import static org.junit.Assert.*;

public class AppTest {
    @Test
    public void quoteTest(){
        String testText = "Charles Dickens";
        String testAuthor = "“Ask no questions, and you'll be told no lies.”";
        String expected = String.format("%s, %s", testText, testAuthor);
        String actual = "Charles Dickens, “Ask no questions, and you'll be told no lies.”";
        assertEquals(expected, actual);
    }

//    @Test public void quoteTest() throws IOException {
//        int n = App.randomNum();
//        Quote expected = App.randomQuote(n);
//        Quote actual = App.randomQuote(n);
//        assertEquals(expected, actual);
//        String testAuthor = "Charles Dickens";
//        String testText = "“Ask no questions, and you'll be told no lies.”";
//        String expected =
//    }
//    @Test
//    public void JsonTest() throws IOException {
//        boolean result = App.main();
//        assertTrue(result);
//
//    }
}
