/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import java.io.*;
import java.nio.file.Files;
import java.nio.file.Paths;
import com.google.gson.Gson;
import java.util.concurrent.ThreadLocalRandom;

public class App {


    public static boolean main() throws IOException{
        Reader reader = Files.newBufferedReader(Paths.get("/Users/cb/codefellows/401/quotes/app/src/main/java/resources/quotes.json"));
        Gson gson = new Gson();
        Quote[] quotes = gson.fromJson(reader, Quote[].class);

        for (Quote quote : quotes){
            int random = ThreadLocalRandom.current().nextInt(0, quotes.length);
            String author = quotes[random].author;
            String text = quotes[random].text;
            String result = text + author;
            System.out.println(result);
            if(result == null){
                return false;
            }
            break;
        }
        reader.close();
        return true;

    }

}
